env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  no-console: 0
  import/extensions: 0
  react/prop-types: 0
  no-unused-vars: 0
  no-param-reassign: 0
  no-shadow: 0
  vue/experimental-script-setup-vars: 0
